// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwb0FYk7s6VTYCzcsx4SJcfY6Py7FDBnU',
    appId: '1:832700163605:web:199afba1503680630f101c',
    messagingSenderId: '832700163605',
    projectId: 'url2goweb',
    authDomain: 'url2goweb.firebaseapp.com',
    storageBucket: 'url2goweb.appspot.com',
    measurementId: 'G-98LJ0FLDV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcyYXFBUMQE8TPVp4e-8S8w1oXmDnwuRQ',
    appId: '1:832700163605:android:f844a008605b0b130f101c',
    messagingSenderId: '832700163605',
    projectId: 'url2goweb',
    storageBucket: 'url2goweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJRQEe2dvs47MbRz3YmKkWkXlGjQ4b64',
    appId: '1:832700163605:ios:5315011061e04fcb0f101c',
    messagingSenderId: '832700163605',
    projectId: 'url2goweb',
    storageBucket: 'url2goweb.appspot.com',
    iosBundleId: 'com.example.url2goweb',
  );
}
